server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - RewritePath=/api/v1/$\{serviceName}, (?<serviceName>.*)
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: product-graphql-redirect
          uri: lb://product-service
          predicates:
            - Path=/api/v1/graphql/products/**
          filters:
            - RewritePath=/api/v1/graphql/products, /api/v1/graphql

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: order-graphql-redirect
          uri: lb://order-service
          predicates:
            - Path=/api/v1/graphql/orders/**
          filters:
            - RewritePath=/api/v1/graphql/orders, /api/v1/graphql