apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafkasv
spec:
  serviceName: kafkasv
  replicas: 1
  selector:
    matchLabels:
      app: kafkasv
  template:
    metadata:
      labels:
        app: kafkasv
    spec:
      containers:
        - name: kafkasv
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: '0'
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'zookeeper-0.zookeeper.default.svc.cluster.local:2181'
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafkasv-0.kafkasv.default.svc.cluster.local:9092,PLAINTEXT_HOST://localhost:9093
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: kafkasv
spec:
  selector:
    app: kafkasv
  ports:
    - name: plain
      protocol: TCP
      port: 9092
    - name: host
      protocol: TCP
      port: 9093