apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: omon4412/notification_image:latest
          ports:
            - containerPort: 8081
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-0.eureka:8761/eureka/
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: spring.kafka.bootstrap-servers
              value: kafkasv-0.kafkasv.default.svc.cluster.local:9092
            - name: spring.kafka.consumer.group-id
              value: vsGroup
            - name: topic.name
              value: notification